Started GET "/articles/1" for ::1 at 2021-11-04 14:44:57 +0300
  [1m[35m (0.1ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  â†³ /usr/lib/ruby/vendor_ruby/web_console/middleware.rb:135
  
ActionController::RoutingError (No route matches [GET] "/articles/1"):
  
actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:135:in `call_app'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:30:in `block in call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `catch'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `call'
/usr/lib/ruby/vendor_ruby/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/lib/ruby/vendor_ruby/rack/method_override.rb:22:in `call'
/usr/lib/ruby/vendor_ruby/rack/runtime.rb:22:in `call'
activesupport (5.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/static.rb:127:in `call'
/usr/lib/ruby/vendor_ruby/rack/sendfile.rb:111:in `call'
railties (5.2.3) lib/rails/engine.rb:524:in `call'
/usr/lib/ruby/vendor_ruby/puma/configuration.rb:227:in `call'
/usr/lib/ruby/vendor_ruby/puma/server.rb:675:in `handle_request'
/usr/lib/ruby/vendor_ruby/puma/server.rb:476:in `process_client'
/usr/lib/ruby/vendor_ruby/puma/server.rb:334:in `block in run'
/usr/lib/ruby/vendor_ruby/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/articles/1" for ::1 at 2021-11-04 14:44:59 +0300
  
ActionController::RoutingError (No route matches [GET] "/articles/1"):
  
actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:135:in `call_app'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:30:in `block in call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `catch'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `call'
/usr/lib/ruby/vendor_ruby/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/lib/ruby/vendor_ruby/rack/method_override.rb:22:in `call'
/usr/lib/ruby/vendor_ruby/rack/runtime.rb:22:in `call'
activesupport (5.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/static.rb:127:in `call'
/usr/lib/ruby/vendor_ruby/rack/sendfile.rb:111:in `call'
railties (5.2.3) lib/rails/engine.rb:524:in `call'
/usr/lib/ruby/vendor_ruby/puma/configuration.rb:227:in `call'
/usr/lib/ruby/vendor_ruby/puma/server.rb:675:in `handle_request'
/usr/lib/ruby/vendor_ruby/puma/server.rb:476:in `process_client'
/usr/lib/ruby/vendor_ruby/puma/server.rb:334:in `block in run'
/usr/lib/ruby/vendor_ruby/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/articles/1" for ::1 at 2021-11-04 14:47:17 +0300
  
ActionController::RoutingError (No route matches [GET] "/articles/1"):
  
actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:135:in `call_app'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:30:in `block in call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `catch'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `call'
/usr/lib/ruby/vendor_ruby/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/lib/ruby/vendor_ruby/rack/method_override.rb:22:in `call'
/usr/lib/ruby/vendor_ruby/rack/runtime.rb:22:in `call'
activesupport (5.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/static.rb:127:in `call'
/usr/lib/ruby/vendor_ruby/rack/sendfile.rb:111:in `call'
railties (5.2.3) lib/rails/engine.rb:524:in `call'
/usr/lib/ruby/vendor_ruby/puma/configuration.rb:227:in `call'
/usr/lib/ruby/vendor_ruby/puma/server.rb:675:in `handle_request'
/usr/lib/ruby/vendor_ruby/puma/server.rb:476:in `process_client'
/usr/lib/ruby/vendor_ruby/puma/server.rb:334:in `block in run'
/usr/lib/ruby/vendor_ruby/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/articles/1" for ::1 at 2021-11-04 14:47:28 +0300
  
ActionController::RoutingError (No route matches [GET] "/articles/1"):
  
actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:135:in `call_app'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:30:in `block in call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `catch'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `call'
/usr/lib/ruby/vendor_ruby/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/lib/ruby/vendor_ruby/rack/method_override.rb:22:in `call'
/usr/lib/ruby/vendor_ruby/rack/runtime.rb:22:in `call'
activesupport (5.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/static.rb:127:in `call'
/usr/lib/ruby/vendor_ruby/rack/sendfile.rb:111:in `call'
railties (5.2.3) lib/rails/engine.rb:524:in `call'
/usr/lib/ruby/vendor_ruby/puma/configuration.rb:227:in `call'
/usr/lib/ruby/vendor_ruby/puma/server.rb:675:in `handle_request'
/usr/lib/ruby/vendor_ruby/puma/server.rb:476:in `process_client'
/usr/lib/ruby/vendor_ruby/puma/server.rb:334:in `block in run'
/usr/lib/ruby/vendor_ruby/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/articles/7" for ::1 at 2021-11-04 14:49:03 +0300
  
ActionController::RoutingError (No route matches [GET] "/articles/7"):
  
actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:135:in `call_app'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:30:in `block in call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `catch'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `call'
/usr/lib/ruby/vendor_ruby/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/lib/ruby/vendor_ruby/rack/method_override.rb:22:in `call'
/usr/lib/ruby/vendor_ruby/rack/runtime.rb:22:in `call'
activesupport (5.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/static.rb:127:in `call'
/usr/lib/ruby/vendor_ruby/rack/sendfile.rb:111:in `call'
railties (5.2.3) lib/rails/engine.rb:524:in `call'
/usr/lib/ruby/vendor_ruby/puma/configuration.rb:227:in `call'
/usr/lib/ruby/vendor_ruby/puma/server.rb:675:in `handle_request'
/usr/lib/ruby/vendor_ruby/puma/server.rb:476:in `process_client'
/usr/lib/ruby/vendor_ruby/puma/server.rb:334:in `block in run'
/usr/lib/ruby/vendor_ruby/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/articles/6" for ::1 at 2021-11-04 14:49:07 +0300
  
ActionController::RoutingError (No route matches [GET] "/articles/6"):
  
actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:135:in `call_app'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:30:in `block in call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `catch'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `call'
/usr/lib/ruby/vendor_ruby/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/lib/ruby/vendor_ruby/rack/method_override.rb:22:in `call'
/usr/lib/ruby/vendor_ruby/rack/runtime.rb:22:in `call'
activesupport (5.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/static.rb:127:in `call'
/usr/lib/ruby/vendor_ruby/rack/sendfile.rb:111:in `call'
railties (5.2.3) lib/rails/engine.rb:524:in `call'
/usr/lib/ruby/vendor_ruby/puma/configuration.rb:227:in `call'
/usr/lib/ruby/vendor_ruby/puma/server.rb:675:in `handle_request'
/usr/lib/ruby/vendor_ruby/puma/server.rb:476:in `process_client'
/usr/lib/ruby/vendor_ruby/puma/server.rb:334:in `block in run'
/usr/lib/ruby/vendor_ruby/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/articles/6" for ::1 at 2021-11-04 14:49:41 +0300
  
ActionController::RoutingError (No route matches [GET] "/articles/6"):
  
actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:135:in `call_app'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:30:in `block in call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `catch'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `call'
/usr/lib/ruby/vendor_ruby/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/lib/ruby/vendor_ruby/rack/method_override.rb:22:in `call'
/usr/lib/ruby/vendor_ruby/rack/runtime.rb:22:in `call'
activesupport (5.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/static.rb:127:in `call'
/usr/lib/ruby/vendor_ruby/rack/sendfile.rb:111:in `call'
railties (5.2.3) lib/rails/engine.rb:524:in `call'
/usr/lib/ruby/vendor_ruby/puma/configuration.rb:227:in `call'
/usr/lib/ruby/vendor_ruby/puma/server.rb:675:in `handle_request'
/usr/lib/ruby/vendor_ruby/puma/server.rb:476:in `process_client'
/usr/lib/ruby/vendor_ruby/puma/server.rb:334:in `block in run'
/usr/lib/ruby/vendor_ruby/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/articles/6" for ::1 at 2021-11-04 14:49:42 +0300
  
ActionController::RoutingError (No route matches [GET] "/articles/6"):
  
actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:135:in `call_app'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:30:in `block in call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `catch'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `call'
/usr/lib/ruby/vendor_ruby/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/lib/ruby/vendor_ruby/rack/method_override.rb:22:in `call'
/usr/lib/ruby/vendor_ruby/rack/runtime.rb:22:in `call'
activesupport (5.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/static.rb:127:in `call'
/usr/lib/ruby/vendor_ruby/rack/sendfile.rb:111:in `call'
railties (5.2.3) lib/rails/engine.rb:524:in `call'
/usr/lib/ruby/vendor_ruby/puma/configuration.rb:227:in `call'
/usr/lib/ruby/vendor_ruby/puma/server.rb:675:in `handle_request'
/usr/lib/ruby/vendor_ruby/puma/server.rb:476:in `process_client'
/usr/lib/ruby/vendor_ruby/puma/server.rb:334:in `block in run'
/usr/lib/ruby/vendor_ruby/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/articles/6" for ::1 at 2021-11-04 14:50:08 +0300
  
ActionController::RoutingError (No route matches [GET] "/articles/6"):
  
actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:135:in `call_app'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:30:in `block in call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `catch'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `call'
/usr/lib/ruby/vendor_ruby/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/lib/ruby/vendor_ruby/rack/method_override.rb:22:in `call'
/usr/lib/ruby/vendor_ruby/rack/runtime.rb:22:in `call'
activesupport (5.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/static.rb:127:in `call'
/usr/lib/ruby/vendor_ruby/rack/sendfile.rb:111:in `call'
railties (5.2.3) lib/rails/engine.rb:524:in `call'
/usr/lib/ruby/vendor_ruby/puma/configuration.rb:227:in `call'
/usr/lib/ruby/vendor_ruby/puma/server.rb:675:in `handle_request'
/usr/lib/ruby/vendor_ruby/puma/server.rb:476:in `process_client'
/usr/lib/ruby/vendor_ruby/puma/server.rb:334:in `block in run'
/usr/lib/ruby/vendor_ruby/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/articles/6" for ::1 at 2021-11-04 14:50:10 +0300
  
ActionController::RoutingError (No route matches [GET] "/articles/6"):
  
actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:135:in `call_app'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:30:in `block in call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `catch'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `call'
/usr/lib/ruby/vendor_ruby/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/lib/ruby/vendor_ruby/rack/method_override.rb:22:in `call'
/usr/lib/ruby/vendor_ruby/rack/runtime.rb:22:in `call'
activesupport (5.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/static.rb:127:in `call'
/usr/lib/ruby/vendor_ruby/rack/sendfile.rb:111:in `call'
railties (5.2.3) lib/rails/engine.rb:524:in `call'
/usr/lib/ruby/vendor_ruby/puma/configuration.rb:227:in `call'
/usr/lib/ruby/vendor_ruby/puma/server.rb:675:in `handle_request'
/usr/lib/ruby/vendor_ruby/puma/server.rb:476:in `process_client'
/usr/lib/ruby/vendor_ruby/puma/server.rb:334:in `block in run'
/usr/lib/ruby/vendor_ruby/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/about/1" for ::1 at 2021-11-04 14:53:34 +0300
  
ActionController::RoutingError (No route matches [GET] "/about/1"):
  
actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:135:in `call_app'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:30:in `block in call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `catch'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `call'
/usr/lib/ruby/vendor_ruby/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/lib/ruby/vendor_ruby/rack/method_override.rb:22:in `call'
/usr/lib/ruby/vendor_ruby/rack/runtime.rb:22:in `call'
activesupport (5.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/static.rb:127:in `call'
/usr/lib/ruby/vendor_ruby/rack/sendfile.rb:111:in `call'
railties (5.2.3) lib/rails/engine.rb:524:in `call'
/usr/lib/ruby/vendor_ruby/puma/configuration.rb:227:in `call'
/usr/lib/ruby/vendor_ruby/puma/server.rb:675:in `handle_request'
/usr/lib/ruby/vendor_ruby/puma/server.rb:476:in `process_client'
/usr/lib/ruby/vendor_ruby/puma/server.rb:334:in `block in run'
/usr/lib/ruby/vendor_ruby/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/about/1" for ::1 at 2021-11-04 15:11:21 +0300
  
ActionController::RoutingError (No route matches [GET] "/about/1"):
  
actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:135:in `call_app'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:30:in `block in call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `catch'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `call'
/usr/lib/ruby/vendor_ruby/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/lib/ruby/vendor_ruby/rack/method_override.rb:22:in `call'
/usr/lib/ruby/vendor_ruby/rack/runtime.rb:22:in `call'
activesupport (5.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/static.rb:127:in `call'
/usr/lib/ruby/vendor_ruby/rack/sendfile.rb:111:in `call'
railties (5.2.3) lib/rails/engine.rb:524:in `call'
/usr/lib/ruby/vendor_ruby/puma/configuration.rb:227:in `call'
/usr/lib/ruby/vendor_ruby/puma/server.rb:675:in `handle_request'
/usr/lib/ruby/vendor_ruby/puma/server.rb:476:in `process_client'
/usr/lib/ruby/vendor_ruby/puma/server.rb:334:in `block in run'
/usr/lib/ruby/vendor_ruby/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/about/1" for ::1 at 2021-11-04 15:11:22 +0300
  
ActionController::RoutingError (No route matches [GET] "/about/1"):
  
actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:135:in `call_app'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:30:in `block in call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `catch'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `call'
/usr/lib/ruby/vendor_ruby/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/lib/ruby/vendor_ruby/rack/method_override.rb:22:in `call'
/usr/lib/ruby/vendor_ruby/rack/runtime.rb:22:in `call'
activesupport (5.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/static.rb:127:in `call'
/usr/lib/ruby/vendor_ruby/rack/sendfile.rb:111:in `call'
railties (5.2.3) lib/rails/engine.rb:524:in `call'
/usr/lib/ruby/vendor_ruby/puma/configuration.rb:227:in `call'
/usr/lib/ruby/vendor_ruby/puma/server.rb:675:in `handle_request'
/usr/lib/ruby/vendor_ruby/puma/server.rb:476:in `process_client'
/usr/lib/ruby/vendor_ruby/puma/server.rb:334:in `block in run'
/usr/lib/ruby/vendor_ruby/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/about/1" for ::1 at 2021-11-04 15:11:23 +0300
  
ActionController::RoutingError (No route matches [GET] "/about/1"):
  
actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:135:in `call_app'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:30:in `block in call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `catch'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `call'
/usr/lib/ruby/vendor_ruby/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/lib/ruby/vendor_ruby/rack/method_override.rb:22:in `call'
/usr/lib/ruby/vendor_ruby/rack/runtime.rb:22:in `call'
activesupport (5.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/static.rb:127:in `call'
/usr/lib/ruby/vendor_ruby/rack/sendfile.rb:111:in `call'
railties (5.2.3) lib/rails/engine.rb:524:in `call'
/usr/lib/ruby/vendor_ruby/puma/configuration.rb:227:in `call'
/usr/lib/ruby/vendor_ruby/puma/server.rb:675:in `handle_request'
/usr/lib/ruby/vendor_ruby/puma/server.rb:476:in `process_client'
/usr/lib/ruby/vendor_ruby/puma/server.rb:334:in `block in run'
/usr/lib/ruby/vendor_ruby/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/articles" for ::1 at 2021-11-04 15:11:50 +0300
  
ActionController::RoutingError (No route matches [GET] "/articles"):
  
actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:135:in `call_app'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:30:in `block in call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `catch'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `call'
/usr/lib/ruby/vendor_ruby/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/lib/ruby/vendor_ruby/rack/method_override.rb:22:in `call'
/usr/lib/ruby/vendor_ruby/rack/runtime.rb:22:in `call'
activesupport (5.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/static.rb:127:in `call'
/usr/lib/ruby/vendor_ruby/rack/sendfile.rb:111:in `call'
railties (5.2.3) lib/rails/engine.rb:524:in `call'
/usr/lib/ruby/vendor_ruby/puma/configuration.rb:227:in `call'
/usr/lib/ruby/vendor_ruby/puma/server.rb:675:in `handle_request'
/usr/lib/ruby/vendor_ruby/puma/server.rb:476:in `process_client'
/usr/lib/ruby/vendor_ruby/puma/server.rb:334:in `block in run'
/usr/lib/ruby/vendor_ruby/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/articles" for ::1 at 2021-11-04 15:12:44 +0300
  
ActionController::RoutingError (No route matches [GET] "/articles"):
  
actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:135:in `call_app'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:30:in `block in call'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `catch'
/usr/lib/ruby/vendor_ruby/web_console/middleware.rb:20:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `call'
/usr/lib/ruby/vendor_ruby/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/lib/ruby/vendor_ruby/rack/method_override.rb:22:in `call'
/usr/lib/ruby/vendor_ruby/rack/runtime.rb:22:in `call'
activesupport (5.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/static.rb:127:in `call'
/usr/lib/ruby/vendor_ruby/rack/sendfile.rb:111:in `call'
railties (5.2.3) lib/rails/engine.rb:524:in `call'
/usr/lib/ruby/vendor_ruby/puma/configuration.rb:227:in `call'
/usr/lib/ruby/vendor_ruby/puma/server.rb:675:in `handle_request'
/usr/lib/ruby/vendor_ruby/puma/server.rb:476:in `process_client'
/usr/lib/ruby/vendor_ruby/puma/server.rb:334:in `block in run'
/usr/lib/ruby/vendor_ruby/puma/thread_pool.rb:135:in `block in spawn_thread'
